-- Issue Reports — public sequential reference number.
--
-- Adds a BIGINT IDENTITY column `issue_no` to the live issue_reports
-- table. This is the user-facing sequential reference shown as
-- "Issue No. 1", "Issue No. 2", etc. The internal UUID `id` stays
-- as the primary key for DB integrity; `issue_no` is purely for
-- display in success messages and the admin list.
--
-- Idempotent — uses IF NOT EXISTS guards. Safe to re-run.
--
-- Run order:
--   1. Run this migration in the Supabase SQL editor.
--   2. Existing rows backfill automatically (IDENTITY assigns
--      sequential values to all current rows the first time the
--      column is added).
--   3. Subsequent inserts get the next value automatically — the
--      application helper does NOT send issue_no on insert.

BEGIN;

-- BIGINT IDENTITY auto-increments on every insert. NOT NULL is
-- enforced by the IDENTITY constraint. The DEFAULT-style identity
-- ("GENERATED BY DEFAULT") lets the application pass an override
-- value if it ever needs to (e.g. for backfills); GENERATED ALWAYS
-- would block any explicit insert.
ALTER TABLE issue_reports
  ADD COLUMN IF NOT EXISTS issue_no BIGINT GENERATED BY DEFAULT AS IDENTITY;

-- Unique index — issue_no is the user-facing reference, must be
-- unique. PostgreSQL's IDENTITY uniqueness is sequence-driven but
-- not formally constrained without an index.
CREATE UNIQUE INDEX IF NOT EXISTS issue_reports_issue_no_idx
  ON issue_reports (issue_no);

COMMIT;

-- Sanity check (run separately):
--   SELECT id, issue_no, status, created_at
--   FROM   issue_reports
--   ORDER  BY issue_no DESC
--   LIMIT  5;
