import type { MetadataRoute } from "next";

/**
 * /sitemap.xml — served by Next from app/sitemap.ts.
 *
 * Phase 1-A: only the public, indexable URLs that exist TODAY. No
 * service / category / area landing pages yet — those land in Phase
 * 2 with their own dynamic generation.
 *
 * lastModified is evaluated at build time (this file is statically
 * generated by default). That is fine for the legal pages — their
 * content changes rarely. When Phase 2 introduces dynamic landing
 * pages, drive their `lastModified` from the underlying provider /
 * category row timestamps instead of a single build timestamp so
 * Google can deprioritise unchanged URLs.
 *
 * priority is advisory only — Google has publicly stated it largely
 * ignores the value. Setting 1.0 on the homepage and 0.3 on the
 * legal pages preserves the intent for crawlers that still honour
 * the field (Bing, Yandex).
 */
export default function sitemap(): MetadataRoute.Sitemap {
  const base = "https://kaunkarega.com";
  const lastModified = new Date();

  return [
    {
      url: `${base}/`,
      lastModified,
      changeFrequency: "weekly",
      priority: 1.0,
    },
    {
      url: `${base}/privacy`,
      lastModified,
      changeFrequency: "yearly",
      priority: 0.3,
    },
    {
      url: `${base}/privacy-policy`,
      lastModified,
      changeFrequency: "yearly",
      priority: 0.3,
    },
    {
      url: `${base}/terms`,
      lastModified,
      changeFrequency: "yearly",
      priority: 0.3,
    },
    {
      url: `${base}/disclaimer`,
      lastModified,
      changeFrequency: "yearly",
      priority: 0.3,
    },
  ];
}
