"use client";

import { useEffect, useState } from "react";
import { Receipt, Download, Clock, ExternalLink } from "lucide-react";

import { useSessionGuard } from "@/lib/useSessionGuard";
import { formatPaiseToRupees } from "@/lib/payments/gst";

// Dedicated provider "My Invoices" page (linked from the menu drawer, not
// embedded in the dashboard). Read-only: lists the authenticated
// provider's own invoices and links to the ownership-checked download
// route. PDFs are generated by the admin Phase 3A flow; here we only show
// pdf_status and a download action once it is 'generated'.
//
// Auth mirrors /provider/notifications: useSessionGuard pings whoami and
// redirects stale sessions; the API enforces provider-ness server-side.

type InvoiceRow = {
  id: number;
  invoice_number: string;
  invoice_date: string;
  plan_code: string;
  taxable_value_paise: number;
  total_tax_paise: number;
  total_paise: number;
  pdf_status: "pending" | "generating" | "generated" | "failed";
};

const PLAN_LABEL: Record<string, string> = {
  regions_5: "5 Regions plan",
  all_jodhpur: "Full Jodhpur plan",
};

function planLabel(code: string): string {
  return PLAN_LABEL[code] ?? code;
}

function money(paise: number): string {
  return `Rs. ${formatPaiseToRupees(paise)}`;
}

function fmtDate(value: string): string {
  const datePart = String(value ?? "").slice(0, 10);
  const [y, m, d] = datePart.split("-");
  return y && m && d ? `${d}-${m}-${y}` : datePart;
}

export default function ProviderInvoicesPage() {
  useSessionGuard({ redirectTo: "/login?next=/provider/invoices" });

  const [invoices, setInvoices] = useState<InvoiceRow[] | null>(null);
  const [loadError, setLoadError] = useState<string | null>(null);

  useEffect(() => {
    let ignore = false;
    const load = async () => {
      try {
        const res = await fetch("/api/provider/invoices", {
          headers: { Accept: "application/json" },
        });
        const data = (await res.json()) as {
          ok?: boolean;
          invoices?: InvoiceRow[];
          error?: string;
        };
        if (ignore) return;
        if (res.ok && data.ok) {
          setInvoices(Array.isArray(data.invoices) ? data.invoices : []);
        } else {
          setLoadError(data.error ?? "Could not load your invoices.");
          setInvoices([]);
        }
      } catch {
        if (ignore) return;
        setLoadError("Could not load your invoices.");
        setInvoices([]);
      }
    };
    void load();
    return () => {
      ignore = true;
    };
  }, []);

  return (
    <main
      data-testid="provider-invoices-page"
      className="min-h-screen bg-[linear-gradient(180deg,#f8fafc_0%,#eef6ff_100%)] px-4 py-8"
    >
      <div className="mx-auto w-full max-w-3xl space-y-6">
        <header className="flex items-center gap-3">
          <span className="inline-flex h-10 w-10 items-center justify-center rounded-full bg-[#003d20]/10 text-[#003d20]">
            <Receipt className="h-5 w-5" />
          </span>
          <div>
            <h1 className="text-xl font-bold text-[#003d20]">My Invoices</h1>
            <p className="text-sm text-slate-500">
              GST tax invoices for your plan payments.
            </p>
          </div>
        </header>

        {invoices === null ? (
          <p
            data-testid="provider-invoices-loading"
            className="rounded-xl border border-slate-100 bg-white px-4 py-6 text-sm text-slate-500"
          >
            Loading your invoices…
          </p>
        ) : loadError ? (
          <p
            data-testid="provider-invoices-error"
            className="rounded-xl border border-amber-200 bg-amber-50 px-4 py-6 text-sm text-amber-700"
          >
            {loadError}
          </p>
        ) : invoices.length === 0 ? (
          <p
            data-testid="provider-invoices-empty"
            className="rounded-xl border border-slate-100 bg-white px-4 py-10 text-center text-sm text-slate-500"
          >
            No invoices yet.
          </p>
        ) : (
          <ul data-testid="provider-invoices-list" className="space-y-3">
            {invoices.map((inv) => {
              const isGenerated = inv.pdf_status === "generated";
              return (
                <li
                  key={inv.id}
                  data-testid={`provider-invoice-row-${inv.id}`}
                  className="rounded-xl border border-slate-100 bg-white p-4 shadow-sm"
                >
                  <div className="flex flex-wrap items-start justify-between gap-3">
                    <div className="space-y-1">
                      <p className="text-sm font-semibold text-[#003d20]">
                        {inv.invoice_number}
                      </p>
                      <p className="text-xs text-slate-500">
                        {fmtDate(inv.invoice_date)} · {planLabel(inv.plan_code)}
                      </p>
                    </div>
                    {isGenerated ? (
                      <div className="flex items-center gap-2">
                        <a
                          data-testid={`provider-invoice-view-${inv.id}`}
                          href={`/api/provider/invoices/${inv.id}/download?disposition=inline`}
                          target="_blank"
                          rel="noopener noreferrer"
                          className="inline-flex items-center gap-2 rounded-lg border border-[#003d20] bg-white px-3 py-2 text-xs font-semibold text-[#003d20] transition hover:bg-[#003d20]/5"
                        >
                          <ExternalLink className="h-4 w-4" />
                          View
                        </a>
                        <a
                          data-testid={`provider-invoice-download-${inv.id}`}
                          href={`/api/provider/invoices/${inv.id}/download?disposition=attachment`}
                          className="inline-flex items-center gap-2 rounded-lg bg-[#003d20] px-3 py-2 text-xs font-semibold text-white transition hover:bg-[#00542b]"
                        >
                          <Download className="h-4 w-4" />
                          Download
                        </a>
                      </div>
                    ) : (
                      <span
                        data-testid={`provider-invoice-status-${inv.id}`}
                        className="inline-flex items-center gap-2 rounded-lg border border-slate-200 bg-slate-50 px-3 py-2 text-xs font-semibold text-slate-500"
                      >
                        <Clock className="h-4 w-4" />
                        {inv.pdf_status === "failed"
                          ? "PDF pending"
                          : "Being generated"}
                      </span>
                    )}
                  </div>

                  <dl className="mt-3 grid grid-cols-3 gap-2 border-t border-slate-100 pt-3 text-center">
                    <div>
                      <dt className="text-[10px] uppercase tracking-wide text-slate-400">
                        Taxable
                      </dt>
                      <dd className="text-sm font-semibold text-slate-700">
                        {money(inv.taxable_value_paise)}
                      </dd>
                    </div>
                    <div>
                      <dt className="text-[10px] uppercase tracking-wide text-slate-400">
                        GST
                      </dt>
                      <dd className="text-sm font-semibold text-slate-700">
                        {money(inv.total_tax_paise)}
                      </dd>
                    </div>
                    <div>
                      <dt className="text-[10px] uppercase tracking-wide text-slate-400">
                        Total
                      </dt>
                      <dd className="text-sm font-bold text-[#003d20]">
                        {money(inv.total_paise)}
                      </dd>
                    </div>
                  </dl>
                </li>
              );
            })}
          </ul>
        )}
      </div>
    </main>
  );
}
